In [15]:
import numpy as np

In [2]:
a = np.array([
    [2.1,3.1,3.9],
    [3.2, 4.5, 3.1]
])

In [3]:
print(a)
print(a.shape)

[[ 2.1  3.1  3.9]
 [ 3.2  4.5  3.1]]
(2, 3)


In [4]:
np.mean(a, axis = 1)

array([ 3.03333333,  3.6       ])

In [6]:
import tensorflow as tf
a = tf.constant(3, dtype=tf.float32, name='const')
b = tf.Variable(0, dtype=tf.float32)
c = tf.assign(b, a+b)
print(a)
a = a + a
print(a)
init = tf.global_variables_initializer()

Tensor("const_2:0", shape=(), dtype=float32)
Tensor("add_3:0", shape=(), dtype=float32)


In [8]:
with tf.Session() as sess:
    sess.run(init)
    print(a+b)
    print(sess.run(c))

Tensor("add_5:0", shape=(), dtype=float32)
3.0


In [ ]:
import sys
sys.executable

In [10]:
import sys
sys.executable

'/home/pirl/anaconda3/envs/tf/bin/python'

In [33]:
np.random.seed(42)
x = tf.placeholder(tf.float32, shape=(), name='x')
y = tf.placeholder(tf.float32, shape=(), name='y')
w = tf.Variable(np.random.randn(), dtype=tf.float32)
a = tf.assign(w, w+x+y)
init = tf.global_variables_initializer()

In [34]:
with tf.Session() as sess:
    sess.run(init)
    for _ in range(0, 10):
        print(sess.run(w))
        sess.run(a, feed_dict={x:1.0, y:2.0})
    print(sess.run(w))

0.49671414
3.496714
6.496714
9.496714
12.496714
15.496714
18.496714
21.496714
24.496714
27.496714
30.496714
