In [1]:
import numpy as np
from scipy import stats
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.stats.proportion import proportions_ztest

In [2]:
df1 = pd.DataFrame({'before':[720,589,780,648,720,589,780,648,780,648]})
df2 = pd.DataFrame({'before':[810,670,790,712,810,670,790,712,790,712]})

In [6]:
t_result = stats.ttest_rel(df1, df2)
t, p = t_result.statistic.round(3), t_result.pvalue.round(3)
# Paired t-test t값 p값 출력
print("Paired t-test")
print("t검정통계량 : {}".format(t))
print("p-value: {}".format(p))

Paired t-test
t검정통계량 : [-5.324]
p-value: [0.]


In [8]:
df1 = pd.DataFrame({'before':[720,589,780,648,720,589,780,648,780,648]})
df2 = pd.DataFrame({'before':[710,580,787,712,750,600,782,670,790,680]})
t_result = stats.ttest_rel(df1, df2)
t, p = t_result.statistic.round(3), t_result.pvalue.round(3)
# Paired t-test t값 p값 출력
print("Paired t-test")
print("t검정통계량 : {}".format(t))
print("p-value: {}".format(p))

Paired t-test
t검정통계량 : [-2.266]
p-value: [0.05]


# P 69

In [11]:
df1 = pd.DataFrame({'A':[892,623,721,678,723,790,720,670,690,771]})
df2 = pd.DataFrame({'B':[721,821,910,678,723,790,711,790,745,891]})
df3 = pd.DataFrame({'C':[621,915,888,721,894,834,841,912,845,889]})

f_result = stats.f_oneway(df1,df2,df3)
f, p = f_result.statistic.round(3), f_result.pvalue.round(3)
print("One-way ANOVA")
print(f)
print(p)

One-way ANOVA
[4.263]
[0.025]


# P70

In [17]:
from statsmodels.stats.proportion import proportions_ztest
count =15
nobs = 100
value = .1
stat, pval = proportions_ztest(count, nobs, value)
print("1 Proportion test")
print("p검정 통계량 :{0:0.3f}".format(stat))
print("p-value:{0:0.3f}".format(pval))

1 Proportion test
p검정 통계량 :1.400
p-value:0.161


# P 72

In [19]:
count = np.array([4,1])
nobs = np.array([1000,1200])

stat, pval = proportions_ztest(count, nobs)
print("2 Proportion test")
print("p검정통계량 : {0:0.3f}".format(stat))
print("p-value : {0:0.3f}".format(pval))

2 Proportion test
p검정통계량 : 1.553
p-value : 0.120


# P 74

In [25]:
df = pd.DataFrame({"HSG":[270,260,236,234], "SS":[228,285,225,262], "SPA":[277,284,231,208]})
chi, pval, dof, expected = stats.chi2_contingency(df.T)

print("chi-square test")
print("chisq : {0:0.3f}".format(chi))
print("p : {0:.3f}".format(pval))
print("d o f : {}".format(dof))
print('expeted value:\n{}'.format(expected.round(3)))

chi-square test
chisq : 13.366
p : 0.038
d o f : 6
expeted value:
[[258.333 276.333 230.667 234.667]
 [258.333 276.333 230.667 234.667]
 [258.333 276.333 230.667 234.667]]


# P 80

In [29]:
strength = [37.6,38.6,37.2,36.4,38.6,39,37.2,36.1,35.9,37.1,36.9,37.5,36.3,38.1,39,36.9,36.8,37.6,33,33.5]
Temp = [14,15,14,16,17,14,17,16,15,16,14,16,18,13,15,17,14,16,20,21]

corr, pval = stats.pearsonr(strength, Temp)
print("Correlation Analysis")
print("corr:{0:0.3f}".format(corr))
print("p:{0:0.3f}".format(pval))

Correlation Analysis
corr:-0.723
p:0.000


In [32]:
#pg 82
minute = [1,2,3,4,4,5,6,6,7,8]
units = [23,29,49,64,74,87,96,97,109,119]

minutes = sm.add_constant(minute)
model = sm.OLS(units, minutes)
result = model.fit()
print(result.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.979
Model:                            OLS   Adj. R-squared:                  0.976
Method:                 Least Squares   F-statistic:                     365.3
Date:                Fri, 25 Jan 2019   Prob (F-statistic):           5.82e-08
Time:                        11:29:22   Log-Likelihood:                -29.401
No. Observations:                  10   AIC:                             62.80
Df Residuals:                       8   BIC:                             63.41
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          7.1712      3.886      1.845      0.1

/home/pirl/anaconda3/lib/python3.7/site-packages/scipy/stats/stats.py:1394: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=10
  "anyway, n=%i" % int(n))


# P 84

In [33]:
minute = [1,2,3,4,4,5,6,6,7,8]
units = [23,29,49,64,74,87,96,97,109,119]

minutes = sm.add_constant(minute)
model = sm.OLS(units, minutes)
result = model.fit()
print(result.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.979
Model:                            OLS   Adj. R-squared:                  0.976
Method:                 Least Squares   F-statistic:                     365.3
Date:                Fri, 25 Jan 2019   Prob (F-statistic):           5.82e-08
Time:                        13:50:13   Log-Likelihood:                -29.401
No. Observations:                  10   AIC:                             62.80
Df Residuals:                       8   BIC:                             63.41
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          7.1712      3.886      1.845      0.1

/home/pirl/anaconda3/lib/python3.7/site-packages/scipy/stats/stats.py:1394: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=10
  "anyway, n=%i" % int(n))


# P93

In [34]:
from numpy.random import randn
np.random.seed(1234)
df = pd.DataFrame(randn(10,2),columns=["A", 'B'])

In [35]:
df

A         B
0  0.471435 -1.190976
1  1.432707 -0.312652
2 -0.720589  0.887163
3  0.859588 -0.636524
4  0.015696 -2.242685
5  1.150036  0.991946
6  0.953324 -2.021255
7 -0.334077  0.002118
8  0.405453  0.289092
9  1.321158 -1.546906

In [38]:
df.iloc[:,[1]]

B
0 -1.190976
1 -0.312652
2  0.887163
3 -0.636524
4 -2.242685
5  0.991946
6 -2.021255
7  0.002118
8  0.289092
9 -1.546906

In [39]:
from numpy.random import randn
np.random.seed(1234)
df = pd.DataFrame(randn(10,4),columns=["A", 'B','C','D'])

In [40]:
df

A         B         C         D
0  0.471435 -1.190976  1.432707 -0.312652
1 -0.720589  0.887163  0.859588 -0.636524
2  0.015696 -2.242685  1.150036  0.991946
3  0.953324 -2.021255 -0.334077  0.002118
4  0.405453  0.289092  1.321158 -1.546906
5 -0.202646 -0.655969  0.193421  0.553439
6  1.318152 -0.469305  0.675554 -1.817027
7 -0.183109  1.058969 -0.397840  0.337438
8  1.047579  1.045938  0.863717 -0.122092
9  0.124713 -0.322795  0.841675  2.390961

In [41]:
df[0:5]

A         B         C         D
0  0.471435 -1.190976  1.432707 -0.312652
1 -0.720589  0.887163  0.859588 -0.636524
2  0.015696 -2.242685  1.150036  0.991946
3  0.953324 -2.021255 -0.334077  0.002118
4  0.405453  0.289092  1.321158 -1.546906

In [42]:
df.loc[:,'A']

0    0.471435
1   -0.720589
2    0.015696
3    0.953324
4    0.405453
5   -0.202646
6    1.318152
7   -0.183109
8    1.047579
9    0.124713
Name: A, dtype: float64

In [53]:
df.iloc[0:1,:2]

A         B
0  0.471435 -1.190976

In [50]:
df.query('A > 0.5')

A         B         C         D
3  0.953324 -2.021255 -0.334077  0.002118
6  1.318152 -0.469305  0.675554 -1.817027
8  1.047579  1.045938  0.863717 -0.122092

In [54]:
pwd

'/home/pirl/Downloads/Data/Classes'

In [56]:

data = pd.read_csv('./FITNESS.csv')

In [57]:
data

NAME GENDER  AGE  AGEGROUP  WEIGHT     OXY  RUNTIME  RUNPULSE  \
0      Donna      F   42        40   68.15  59.571     8.17       166   
1     Gracie          38        30   81.87  60.055     8.63       170   
2     Luanne      F   43        40   85.84  54.297     8.65       156   
3       Mimi      F   50        50   70.87  54.625     8.92       146   
4      Chris      M   49        40   70.00  49.156     8.95       180   
5      Allen      M   38        30   89.02  49.874     9.22       178   
6      Nancy      F   49        40   76.32  48.673     9.40       186   
7      Patty      F   52        50   76.32  45.441     9.63       164   
8    Suzanne      F   57        50   59.08  50.545     9.93       148   
9     Teresa      F   51        50   77.91  46.672    10.00       162   
10       Bob      M   39        30   75.07  45.313    10.07       185   
11  Harriett      F   49        40   73.37  50.388    10.08       168   
12      Jane      F   44        40   73.03  50.541    10.13       168   
13    Harold      M   48        40   91.63  46.774    10.25       162   
14     Sammy      M   54        50   83.12  51.855    10.33       166   
15     Buffy      F   52        50   73.71  45.790    10.47       186   
16     Trent      M   38        30   82.78  47.467    10.50       170   
17    Jackie      F   47        40   79.15  47.273    10.60       162   
18     Ralph      M   43        40   66.00  49.091    10.85       162   
19      Jack      M   51        50   69.63  40.836    10.95       168   
20     Annie      F   51        50   67.25  45.118    11.08       172   
21      Kate      F   45        40   66.45  44.754    11.12       176   
22      Carl      M   54        50   79.38  46.080    11.17       156   
23       Don      M   44        30   89.47  44.609    11.37       178   
24     Effie      F   48        40   61.24  47.920    11.50       170   
25    George      M   37        30   77.45  44.811    11.63       176   
26      Iris      F   39        30   75.98  45.681    11.95       176   
27      Mark      M   57        50   73.37  39.407    12.63       174   
28     Steve      M   54        50   91.63  39.203    12.88       168   
29    Vaughn      M   44        40   81.42  39.442    13.08       174   
30   William      M   45        40   87.66  37.388    14.03       186   

    RSTPULSE  MAXPULSE  
0         40       172  
1         48       186  
2         45       168  
3         48       155  
4         44       185  
5         55       180  
6         56       188  
7         48       166  
8         49       155  
9         48       168  
10        62       185  
11        67       168  
12        45       168  
13        48       164  
14        50       170  
15        59       188  
16        53       172  
17        47       164  
18        64       170  
19        57       172  
20        48       172  
21        51       176  
22        62       165  
23        62       182  
24        52       176  
25        58       176  
26        70       180  
27        58       176  
28       144       172  
29        63       176  
30        56       192

In [58]:
data.groupby(['GENDER','AGEGROUP']).agg('mean')

AGE     WEIGHT        OXY   RUNTIME  RUNPULSE  \
GENDER AGEGROUP                                                        
       30        38.000000  81.870000  60.055000   8.63000     170.0   
F      30        39.000000  75.980000  45.681000  11.95000     176.0   
       40        45.875000  72.943750  50.427125   9.95625     169.0   
       50        52.166667  70.856667  48.031833  10.00500     163.0   
M      30        39.200000  82.758000  46.414800  10.55800     177.4   
       40        45.800000  79.342000  44.370200  11.43200     172.8   
       50        54.000000  79.426000  43.476200  11.59200     166.4   

                 RSTPULSE    MAXPULSE  
GENDER AGEGROUP                        
       30          48.000  186.000000  
F      30          70.000  180.000000  
       40          50.375  172.500000  
       50          50.000  167.333333  
M      30          58.000  179.000000  
       40          55.000  177.400000  
       50          74.200  171.000000